#*** CONFIG ***#
#---- DB CONFIG ----#
db_server: 192.168.1.131
db_user: "root"
db_pass: ""
db_name: "nepalrelief"
db_driver: "pdo_mysql"
#---- SMS DRIVER CONFIG ---#
sms_driver: "Kaarisaa\Senders\Dhiraagu"
sms_user: ""
sms_pass: ""
#---- EMAIL DRIVER CONFIG --#
email_driver: "Kaarisaa\Drivers\Send"
email_api_token: "vJn9Xl7YhPsIK7HXezBU9Q"
