#!/usr/bin/env php
<?php

/**
 * Console Task Runner
 * @author Ahmed Ali <ajaaibu@gmail.com>
 * @date 27-04-2014 01:57 AM
 */

// set to run indefintely if needed
set_time_limit(0);

date_default_timezone_set("Indian/Maldives");

// include the composer autoloader
require_once __DIR__ .'/../vendor/autoload.php';

use Kaarisaa\Console\KaarisaaConsole;

use Symfony\Component\Yaml\Yaml;

$configFile = __DIR__.'/../config.yml';

$config = Yaml::parse(file_get_contents($configFile));

$app = new KaarisaaConsole();
$app->setConfig($config);
$app->loadCommands();
$app->run();
